import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Airbnb || Authentication system!!",
  description: "Generated by github.com/muhamash ; Instructed by LWS(learn with sumit)",
};

export default async function layout ( { children }: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <>
            {children}
        </>
    );
}
