import { auth } from "@/auth";
import BookingListCard from "@/components/bookings/BookingListCard";
import Empty from "@/components/bookings/Empty";
import { fetchDictionary, fetchUserBookings } from "@/utils/fetchFunction";
import type { Metadata } from "next";
import { Params } from "next/dist/shared/lib/router/utils/route-matcher";

export const metadata: Metadata = {
  title: "Airbnb || Booking list",
  description: "Generated by github.com/muhamash ; Instructed by LWS(learn with sumit)",
};

interface BookingsProps
{
  params: Params;
}

export default async function Bookings ({params}: BookingsProps)
{
  const session: Session | null = await auth();
  const usersBookings = await fetchUserBookings( session?.user?.id );
  const language = await fetchDictionary( params?.lang );
  // console.log( session );

  return (
    <div className="max-w-4xl mx-auto px-4 py-[130px] md:py-[100px]">
      <h1 className="text-3xl font-bold mb-6">{language?.booking?.title}</h1>
      <div className="space-y-4">
        {
          usersBookings?.bookings && usersBookings?.bookings?.length !== 0 ? (
            usersBookings?.bookings?.map( book => (
              <BookingListCard hotelImage={book?.thumbnail} title={book?.hotelName} hotelId={book?.hotelId} bookingId={book?._id} bookingDate={book?.createdAt} key={book?._id} lang={ params?.lang } />
            ) )
          ) : (
              <Empty text={ language?.booking?.text } no={ language?.booking?.no } ex={ language?.booking?.ex }/>
          )
        }
      </div>
    </div>
  );
}
