/* eslint-disable @next/next/no-img-element */
import { kanit, playfairDisplay, rubik, ubuntu } from "@/components/fonts/font";
import { dbConnect } from "@/services/mongoDB";
import type { Metadata } from "next";
import type { Params } from "next/dist/shared/lib/router/utils/route-matcher";
import "../globals.css";

export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by github.com/muhamash ; Instructed by LWS(learn with sumit)",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Params;
}> )
{
  // console.log(params)
  await dbConnect();
  // console.log(connection.name)
  
  return (
    <html lang={params?.lang}>
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        />
      </head>
      <body
        className={`${ kanit.className } ${ playfairDisplay.className } ${ rubik.className } ${ ubuntu.className } antialiased bg-gray-100 relative`}
      >
        <div className="absolute inset-0 bg-cover bg-center">
          <img
            alt="Login background"
            src="/homeBg.jpg"
            layout="fill"
            objectFit="cover"
            className="filter blur-[15px] brightness-90"
          />
        </div>
        {/* <Nav params={params} /> */}
        <div className="relative z-10">
          {children}
        </div>
        {/* <Footer params={params} /> */}
      </body>
    </html>
  );
};
