import Nav from "@/components/common/Nav";
import { kanit, playfairDisplay, rubik, ubuntu } from "@/components/fonts/font";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Airbnb || Home",
  description: "Generated by github.com/muhamash ; Instructed by LWS(learn with sumit)",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
}> )
{
  // console.log(params)
  return (
    <html lang={params?.lang}>
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${ kanit.className } ${ playfairDisplay.className } ${ rubik.className } ${ ubuntu.className } antialiased`}
      >
        <Nav params={ params } />
        {children}
      </body>
    </html>
  );
};
